In [2]:
import numpy as np
import pandas as pd

In [3]:
# https://www.kaggle.com/jmmvutu/eda-online-c2c-fashion-store-user-behaviour
# https://www.kaggle.com/kerneler/starter-e-commerce-users-of-a-french-4b0f4745-8/notebook
df = pd.read_csv('/Users/jsialell/Ironhack/project_curry/Julien/6M-0K-99K.users.dataset.public.csv')

In [4]:
df.head()

,identifierHash,type,country,language,socialNbFollowers,socialNbFollows,socialProductsLiked,productsListed,productsSold,productsPassRate,...,civilityTitle,hasAnyApp,hasAndroidApp,hasIosApp,hasProfilePicture,daysSinceLastLogin,seniority,seniorityAsMonths,seniorityAsYears,countryCode
0,-7279641312655250028,user,Etats-Unis,en,3,8,0,0,0,0.0,...,mrs,False,False,False,True,709,3205,106.83,8.9,us
1,-1456013578740053406,user,Allemagne,de,3,8,0,0,0,0.0,...,mrs,False,False,False,True,709,3205,106.83,8.9,de
2,9006282053848196165,user,Suède,en,3,8,0,0,0,0.0,...,mr,True,False,True,True,689,3205,106.83,8.9,se
3,-7154634866120535654,user,Turquie,en,3,8,0,0,0,0.0,...,mrs,False,False,False,True,709,3205,106.83,8.9,tr
4,2858299215060733023,user,France,en,3,8,0,0,0,0.0,...,mr,True,False,True,True,709,3205,106.83,8.9,fr

In [5]:
df.dtypes

identifierHash           int64
type                    object
country                 object
language                object
socialNbFollowers        int64
socialNbFollows          int64
socialProductsLiked      int64
productsListed           int64
productsSold             int64
productsPassRate       float64
productsWished           int64
productsBought           int64
gender                  object
civilityGenderId         int64
civilityTitle           object
hasAnyApp                 bool
hasAndroidApp             bool
hasIosApp                 bool
hasProfilePicture         bool
daysSinceLastLogin       int64
seniority                int64
seniorityAsMonths      float64
seniorityAsYears       float64
countryCode             object
dtype: object

In [6]:
df.describe

<bound method NDFrame.describe of             identifierHash  type     country language  socialNbFollowers  \
0     -7279641312655250028  user  Etats-Unis       en                  3
1     -1456013578740053406  user   Allemagne       de                  3
2      9006282053848196165  user       Suède       en                  3
3     -7154634866120535654  user     Turquie       en                  3
4      2858299215060733023  user      France       en                  3
...                    ...   ...         ...      ...                ...
98908 -5324380437900495747  user  Etats-Unis       fr                  3
98909 -5607668753771114442  user      France       fr                  3
98910   350630276238833248  user    Belgique       en                  3
98911  2006580738726207028  user      Italie       it                  3
98912 -7621316584087253691  user      Guinée       fr                  3

       socialNbFollows  socialProductsLiked  productsListed  productsSold  \
0                    8                    0               0             0
1                    8                    0               0             0
2                    8                    0               0             0
3                    8                    0               0             0
4                    8                    0               0             0
...                ...                  ...             ...           ...
98908                8                    0               0             0
98909                8                    0               0             0
98910                8                    0               0             0
98911                8                    0               0             0
98912                8                    0               0             0

       productsPassRate  ...  civilityTitle  hasAnyApp hasAndroidApp  \
0                   0.0  ...            mrs      False         False
1                   0.0  ...            mrs      False         False
2                   0.0  ...             mr       True         False
3                   0.0  ...            mrs      False         False
4                   0.0  ...             mr       True         False
...                 ...  ...            ...        ...           ...
98908               0.0  ...             mr      False         False
98909               0.0  ...             mr       True         False
98910               0.0  ...             mr       True          True
98911               0.0  ...            mrs      False         False
98912               0.0  ...             mr       True         False

       hasIosApp hasProfilePicture  daysSinceLastLogin  seniority  \
0          False              True                 709       3205
1          False              True                 709       3205
2           True              True                 689       3205
3          False              True                 709       3205
4           True              True                 709       3205
...          ...               ...                 ...        ...
98908      False              True                 708       3204
98909       True              True                 695       3204
98910      False              True                 520       3204
98911      False              True                 267       3204
98912       True              True                 561       3204

       seniorityAsMonths  seniorityAsYears  countryCode
0                 106.83               8.9           us
1                 106.83               8.9           de
2                 106.83               8.9           se
3                 106.83               8.9           tr
4                 106.83               8.9           fr
...                  ...               ...          ...
98908             106.80               8.9           us
98909             106.80               8.9           fr
98910             106.80               8.9           be
98911             106.80               8.9           it
98912             106.80               8.9           gn

[98913 rows x 24 columns]>

In [21]:
# active users = prospective buyers or prospective sellers
# prospective buyers: those interacted with products of others with a like/wishlist/purchase
# prospective sellers: those having at least one product for sale.

active_users_julien = df.loc[((df['socialProductsLiked'] !=0) | (df['productsListed'] !=0)) | (df['productsBought'] !=0) | (df['productsSold'] !=0) | (df["productsWished"] != 0)]
active_users_julien

,identifierHash,type,country,language,socialNbFollowers,socialNbFollows,socialProductsLiked,productsListed,productsSold,productsPassRate,...,civilityTitle,hasAnyApp,hasAndroidApp,hasIosApp,hasProfilePicture,daysSinceLastLogin,seniority,seniorityAsMonths,seniorityAsYears,countryCode
6,-7877915015908472168,user,Royaume-Uni,en,3,8,4,0,0,0.0,...,mrs,False,False,False,True,591,3205,106.83,8.9,gb
17,-8231936648814680895,user,Danemark,en,3,8,370,0,0,0.0,...,mrs,False,False,False,True,42,3205,106.83,8.9,dk
18,5663923945758514393,user,Etats-Unis,en,3,8,1,0,0,0.0,...,mrs,False,False,False,True,32,3205,106.83,8.9,us
27,-3483039296670050121,user,Allemagne,de,3,8,27,0,0,0.0,...,mr,True,False,True,True,669,3205,106.83,8.9,de
29,3451396970677435825,user,Suisse,en,3,8,0,0,0,0.0,...,mrs,True,True,False,True,463,3205,106.83,8.9,ch
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98889,4508710134224075356,user,France,fr,3,8,1,0,0,0.0,...,mrs,False,False,False,True,477,3204,106.80,8.9,fr
98896,4715935376764926056,user,Allemagne,en,3,8,10,0,0,0.0,...,mrs,True,False,True,True,15,3204,106.80,8.9,de
98898,839748404208280164,user,France,fr,3,8,5,0,0,0.0,...,mrs,False,False,False,True,192,3204,106.80,8.9,fr
98901,7257878909040060228,user,Espagne,es,3,8,31,0,0,0.0,...,mrs,False,False,False,True,13,3204,106.80,8.9,es
98905,3164321379397826945,user,Etats-Unis,en,3,8,6,0,0,0.0,...,mrs,False,False,False,True,655,3204,106.80,8.9,us

In [20]:
# active_users_brian = df.loc[(df["productsListed"] !=0)|(df["productsSold"] !=0)|(df["productsWished"]!=0)|(df["productsBought"]!=0)|(df["socialProductsLiked"]!=0)|(df["socialNbFollows"]>8)]

In [22]:
# Saving the active_users_julien DataFrame as a csv. file
active_users_julien.to_csv("/Users/jsialell/Ironhack/project_curry/Julien/active_users_julien.csv", index=False)

In [24]:
"""Sellers:
Exclusive Sellers 100% Sold and 0% Bought, so: 1:0
Mainly Sellers 99% to 70% Sold , so 99:1 till 70:30

Buyers:
Exclusive Buyers 100% Bought vs. 0% Sold, so 1:0
Mainly Buyers 99% to 70% Bought,so 99:1 till 70:30

Sellers and Buyers:
70% Sold ><70% Bought, so: 69 Sold : 31 Bought till 69 Bought : 31 Sold
all here would be: People who bought 3 things and sold three things (50:50)

Social:
0% buy and 0% sold"""

'Sellers:\nExclusive Sellers 100% Sold and 0% Bought, so: 1:0\nMainly Sellers 99% to 70% Sold , so 99:1 till 70:30\n\nBuyers:\nExclusive Buyers 100% Bought vs. 0% Sold, so 1:0\nMainly Buyers 99% to 70% Bought,so 99:1 till 70:30\n\nSellers and Buyers:\n70% Sold ><70% Bought, so: 69 Sold : 31 Bought till 69 Bought : 31 Sold\nall here would be: People who bought 3 things and sold three things (50:50)\n\nSocial:\n0% buy and 0% sold'

In [ ]:
# Exclusive buyers: if ((df['productsSold'] == 0) & (df['productsBought'] != 0))
# Mainly buyers: if ((df['productsSold'] != 0) & (df['productsBought'] != 0) & ((df['productsBought']/df['productsSold']) >= 3))
# Sellers and buyer: if ((df['productsSold'] != 0) & (df['productsBought'] != 0) & ((df['productsBought']/df['productsSold']) < 3) & ((df['productsBought']/df['productsSold']) > 1/3))
# Mainly sellers: if ((df['productsSold'] != 0) & (df['productsBought'] != 0) & ((df['productsBought']/df['productsSold']) <= 1/3))
# Exclusive sellers: if ((df['productsSold'] != 0) & (df['productsBought'] == 0))
# Social users: if ((df['productsSold'] == 0) & (df['productsBought'] == 0))

In [27]:
df= df.assign(buyer_seller_ration=pd.NA)

In [44]:
df['buyer_seller_ratio']=df['productsSold']/df['productsBought']

In [30]:
# Mainly users
active_users_julien.loc[(df['productsSold'] != 0) & (df['productsBought'] != 0) & ((df['productsBought']/df['productsSold']) >= 3)].describe()

,identifierHash,socialNbFollowers,socialNbFollows,socialProductsLiked,productsListed,productsSold,productsPassRate,productsWished,productsBought,civilityGenderId,daysSinceLastLogin,seniority,seniorityAsMonths,seniorityAsYears
count,1.560000e+02,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000
mean,6.003058e+16,11.070513,14.602564,225.371795,1.782051,2.083333,24.733974,112.679487,20.871795,1.788462,63.660256,3065.794872,102.192949,8.515897
std,5.680450e+18,10.111707,22.013099,723.188970,3.417781,2.047684,40.098444,279.425955,43.183886,0.440082,119.941841,168.976643,5.632291,0.469345
min,-9.081124e+18,3.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,3.000000,1.000000,11.000000,2852.000000,95.070000,7.920000
25%,-5.060344e+18,5.000000,8.000000,6.000000,0.000000,1.000000,0.000000,3.000000,4.000000,2.000000,11.000000,2856.750000,95.222500,7.937500
50%,5.792023e+17,8.000000,9.000000,40.500000,0.000000,1.000000,0.000000,13.500000,9.000000,2.000000,14.000000,3198.000000,106.600000,8.880000
75%,4.852494e+18,12.000000,12.000000,162.500000,2.250000,2.000000,63.375000,78.250000,19.000000,2.000000,45.750000,3202.000000,106.730000,8.890000
max,9.187045e+18,65.000000,174.000000,5979.000000,26.000000,12.000000,100.000000,1916.000000,405.000000,3.000000,618.000000,3205.000000,106.830000,8.900000

In [47]:
active_users_julien.loc[(df['productsSold'] == 0) & (df['productsListed'] !=0) & (df['productsBought'] ==0)]

,identifierHash,type,country,language,socialNbFollowers,socialNbFollows,socialProductsLiked,productsListed,productsSold,productsPassRate,...,civilityTitle,hasAnyApp,hasAndroidApp,hasIosApp,hasProfilePicture,daysSinceLastLogin,seniority,seniorityAsMonths,seniorityAsYears,countryCode
196,3609646979955471261,user,Etats-Unis,en,4,8,7,2,0,0.0,...,mrs,False,False,False,True,60,3205,106.83,8.9,us
986,95744281579333368,user,France,fr,3,9,0,1,0,0.0,...,mrs,True,False,True,True,686,3205,106.83,8.9,fr
996,-6315444790278179623,user,Royaume-Uni,en,3,8,0,2,0,0.0,...,mrs,False,False,False,True,147,3204,106.80,8.9,gb
1020,7290535961460763322,user,Allemagne,de,3,8,64,4,0,0.0,...,mrs,True,False,True,True,11,3204,106.80,8.9,de
1166,8128477750710993644,user,Italie,it,4,8,0,1,0,0.0,...,mrs,False,False,False,True,708,3204,106.80,8.9,it
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97175,5892886467111106900,user,Italie,it,6,8,28,1,0,0.0,...,mrs,True,False,True,True,11,3204,106.80,8.9,it
98054,-7867807660818823282,user,Espagne,es,6,8,0,1,0,0.0,...,mrs,False,False,False,True,32,3204,106.80,8.9,es
98235,4519395251693097964,user,Italie,it,3,8,3,1,0,0.0,...,mr,True,True,False,True,15,3204,106.80,8.9,it
98623,-4664219392170061284,user,France,fr,5,8,0,1,0,0.0,...,mrs,True,False,True,True,17,3204,106.80,8.9,fr
98693,-1981884820122986522,user,Autriche,de,5,8,0,1,0,0.0,...,mr,True,False,True,True,708,3204,106.80,8.9,at

In [39]:
df_active = df.loc[(df["productsListed"] !=0)|(df["productsSold"] !=0)|(df["productsWished"]!=0)|(df["productsBought"]!=0)|(df["socialProductsLiked"]!=0)|(df["socialNbFollows"]>8)]

In [48]:
"""def buyer_seller_ratio(df['buyer_seller_ratio']):
    if ((df['productsSold'] == 0) & (df['productsBought'] != 0)): #exclusive buyers: 0 product sold and at least 1 product bought
        df['buyer_seller_ratio'] = df['productsBought']
    elif ((df['productsSold'] != 0) & (df['productsBought'] != 0) & ((df['productsBought']/df['productsSold']) >= 3)): # mainly buyers: at least 1 product sold and at 
        df[buyer_seller_ratio'] = (df['productsBought']/df['productsSold'])
    elif """

"def buyer_seller_ratio(df['buyer_seller_ratio']):\n    if ((df['productsSold'] == 0) & (df['productsBought'] != 0)): #exclusive buyers: 0 product sold and at least 1 product bought\n        df['buyer_seller_ratio'] = df['productsBought']\n    elif ((df['productsSold'] != 0) & (df['productsBought'] != 0) & ((df['productsBought']/df['productsSold']) >= 3)): # mainly buyers: at least 1 product sold and at \n        df[buyer_seller_ratio'] = (df['productsBought']/df['productsSold'])\n    elif "